# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='music.Genre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='music.Album'),
        ),
    ]
