# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20161212_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file_type',
            field=models.CharField(choices=[('mp3', 'mp3'), ('wav', 'wav'), ('flac', 'flac'), ('ogg', 'ogg')], default='mp3', max_length=7),
        ),
    ]
