# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20161212_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_icon',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
