# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20161212_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_icon',
            field=models.ImageField(blank=True, null=True, storage='/album/', upload_to=b''),
        ),
    ]
